### ISSUE TITLE
Why so many permissions?

### ISSUE THREAD

**Issue by renatobellotti** [flathub/io.atom.Atom#104]
I have some questions regarding the permissions. Are all of them really needed?

- ``--device=all``
- ``--talk-name=org.freedesktop.secrets``
- ``--env=ELECTRON_TRASH=this-is-a-workaround``
   Any information why this is needed? E. g. a comment?

**Comment by cpba** [comment]
It's all relative.

`--device=all` was added in order to allow access to usb devices, such as for arduino development and other common use cases. Whether it's needed depends on what you do.

`--talk-name=org.freedesktop.secrets` without this atom won't be able to talk to your keyring. Atom would still work if you were to disable it, but you'd have to manually manage your keys (and possibly silence a couple errors that pop up, I can't quite remember)

`--env=ELECTRON_TRASH=this-is-a-workaround` this is not a permission, it just sets an env variable to a bogus value. Presumably to fix some issue, but I can't tell you what it was or whether it's still relevant. For what it's worth, here's the commit where it was added: https://github.com/flathub/io.atom.Atom/commit/39e896ad293ac79be1871bd2f1ff272c461c3903

**Comment by renatobellotti** [comment]
Thanks for the clarifications! I'm not very familiar with Flatpak, and device=all is mentioned to be used with cameras, so I thought asking might not hurt. Bit now it makes sense.
