### ISSUE TITLE
Update to 1.38.0

### ISSUE THREAD

**Issue by ai** [flathub/io.atom.Atom#56]
The new version of Atom was released and we need to release flatpak for it

https://blog.atom.io/2019/07/23/atom-1-39.html

**Comment by cpba** [comment]
Updating to 1.39.0 is in my to do list, along with providing atom nightly
through our beta channel, I just haven't had time to do either.

If you want to open a pull request and do the testing I'll make sure to
merge it.

**Comment by ai** [comment]
Sure, I can make PR.

But what CLI tool was used for `sha256` checksum in manifest? `sha256sum` makes different result for https://github.com/flathub/io.atom.Atom/commit/6a7f75d2b9ad4d97260bceb5a1b247a82ed301ef#diff-74c5d7a1539ea5609ea30f27df21356aR70

**Comment by cpba** [comment]
They are most likely created with regular old gnu sha256sum, but that
shouldn't make any difference, as long as the hash is valid flatpak-builder
will take it.

If you're getting a different hash it's often because you have a different
version, they release all packages with the exact same name so it can get a
bit confusing.

**Comment by ai** [comment]
Thanks. I made PR https://github.com/flathub/io.atom.Atom/pull/57
