### ISSUE TITLE
Support ~/.atom config directory

### ISSUE THREAD

**Issue by davidmnoriega** [flathub/io.atom.Atom#63]
Giving the flatpak version of atom a try and noticed that the atom config dir is now in `~/.var/app/io.atom.Atom/data`. This issue https://github.com/flatpak/flatpak-docs/issues/109 seems to imply the use of `--persist` could make use of `~/.atom` once more? I think that would mean using `--perist=.atom` with `ATOM_HOME=$XDG_DATA_HOME/.atom`?

**Comment by TingPing** [comment]
`--persist` cannot work with `--filesystem=host`.

Honestly this is just where private settings go in a Flatpak world so I suggest accepting it.

**Comment by cpba** [comment]
`--persist` is only a workaround meant for applications that use hardcoded paths, it does the opposite of what you want. It works by letting the application believe it is writing to `~/.whatever` but actually writing to `~/.var/app/<app-id>/.whatever`, we don't need this for atom because it uses an env variable.

@davidmnoriega If you *really* want to use `~/.atom` as your conf path, you don't need `--persist` at all. Atom already has full filesystem access, just set `$ATOM_HOME` to whatever you want it to be and it'll work. However, there is no real advantage to doing this, so I wouldn't really recommend it.

**Comment by davidmnoriega** [comment]
Ah ok, makes sense
